variables:
  buildConfiguration: 'Release'

jobs:

- job: buildandtest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
    - script: dotnet build --configuration $(buildConfiguration)
      displayName: 'dotnet build $(buildConfiguration)'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true

    # deploy to Azure Web App staging
    - task: AzureWebApp@1
      inputs:
            azureSubscription: 'capgeminiaz400Devops26(6)(87fce128-be33-4930-bafe-f9510c10e637)'
            appType: 'webApp'
            appName: 'WebAppDotNetCoreDemo21Staging'
            deploymentMethod: 'auto'
      

- job: deploy
  pool:
    vmImage: 'ubuntu-latest'
  dependsOn: buildandtest
  condition: succeeded()
  steps:

  # download the artifact drop from the previous job
  - task: DownloadBuildArtifacts@0
    inputs:
      artifactName: drop

  # deploy to Azure Web App production
  - task: AzureWebApp@1
    inputs:
          azureSubscription: 'capgeminiaz400Devops26(6)(87fce128-be33-4930-bafe-f9510c10e637)'
          appType: 'webApp'
          appName: 'WebAppDotNetCoreDemo21'
          deploymentMethod: 'auto'

      
